/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author mitra
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    Person person;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Person p) {
        person = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfirst = new javax.swing.JTextField();
        lblfirst = new javax.swing.JLabel();
        lbllast = new javax.swing.JLabel();
        txtlast = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        lbllicno = new javax.swing.JLabel();
        txtlicno = new javax.swing.JTextField();
        lbllicst = new javax.swing.JLabel();
        txtlicst = new javax.swing.JTextField();
        lblssn = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        lblprof = new javax.swing.JLabel();
        txtprof = new javax.swing.JTextField();
        lblblood = new javax.swing.JLabel();
        txtblood = new javax.swing.JTextField();
        lblhob = new javax.swing.JLabel();
        txthob = new javax.swing.JTextField();
        lblFav = new javax.swing.JLabel();
        txtfav = new javax.swing.JTextField();
        lblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        lblheight = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        lbladd1 = new javax.swing.JLabel();
        txtadd1 = new javax.swing.JTextField();
        lbladd2 = new javax.swing.JLabel();
        txtadd2 = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        lblzip = new javax.swing.JLabel();
        txtzip = new javax.swing.JTextField();
        lbltel = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        lblfax = new javax.swing.JLabel();
        txtfax = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        lblfirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfirst.setText("First Name");

        lbllast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllast.setText("Last Name");

        lblemail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblemail.setText("Email");

        lblphone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphone.setText("Phone");

        lbllicno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllicno.setText("DL License No");

        lbllicst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllicst.setText("DL License State");

        lblssn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblssn.setText("SSN");

        lblprof.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprof.setText("Profession");

        lblblood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblblood.setText("Blood group");

        lblhob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhob.setText("Hobbies");

        lblFav.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFav.setText("Favourite Food");

        lblgender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblgender.setText("Gender");

        lblheight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblheight.setText("Height");

        txtheight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtheightActionPerformed(evt);
            }
        });

        lbladd1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladd1.setText("Address 1");

        lbladd2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladd2.setText("Address 2");

        lblcity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcity.setText("City");

        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });

        lblstate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblstate.setText("State");

        lblzip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblzip.setText("ZIP");

        lbltel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltel.setText("Tel Number");

        lblfax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfax.setText("Fax Number");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Personal Information");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblprof)
                    .addComponent(lbladd2)
                    .addComponent(lblblood)
                    .addComponent(lblcity)
                    .addComponent(lblhob)
                    .addComponent(lblstate)
                    .addComponent(lblFav)
                    .addComponent(lblzip)
                    .addComponent(lblgender)
                    .addComponent(lbltel)
                    .addComponent(lblfirst)
                    .addComponent(lbllast)
                    .addComponent(lblheight)
                    .addComponent(lblemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbllicno)
                    .addComponent(lbllicst)
                    .addComponent(lblssn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladd1)
                    .addComponent(lblfax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtadd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtblood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlicno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlicst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(216, 216, 216))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblFav, lbladd1, lbladd2, lblblood, lblcity, lblemail, lblfax, lblfirst, lblgender, lblheight, lblhob, lbllast, lbllicno, lbllicst, lblphone, lblprof, lblssn, lblstate, lbltel, lblzip});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtadd1, txtadd2, txtblood, txtcity, txtemail, txtfav, txtfax, txtfirst, txtgender, txtheight, txthob, txtlast, txtlicno, txtlicst, txtphone, txtprof, txtssn, txtstate, txttel, txtzip});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfirst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblphone))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllicno)
                    .addComponent(txtlicno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllicst)
                    .addComponent(txtlicst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblssn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprof)
                    .addComponent(txtprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtblood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblblood))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txthob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFav))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgender)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblheight)
                    .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladd1)
                    .addComponent(txtadd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladd2)
                    .addComponent(txtadd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblzip))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltel)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfax)
                    .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFav, lbladd1, lbladd2, lblblood, lblcity, lblemail, lblfax, lblfirst, lblgender, lblheight, lblhob, lbllast, lbllicno, lbllicst, lblphone, lblprof, lblssn, lblstate, lbltel, lblzip});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtadd1, txtadd2, txtblood, txtcity, txtemail, txtfav, txtfax, txtfirst, txtgender, txtheight, txthob, txtlast, txtlicno, txtlicst, txtphone, txtprof, txtssn, txtstate, txttel, txtzip});

    }// </editor-fold>//GEN-END:initComponents

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtheightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtheightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtheightActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String first = txtfirst.getText();
        String last = txtlast.getText();
        String email = txtemail.getText();
        String phone = txtphone.getText();
        String licno = txtlicno.getText();
        String licst = txtlicst.getText();
        String ssn = txtssn.getText();
        String prof = txtprof.getText();
        String blood = txtblood.getText();
        String hob = txthob.getText();
        String fav = txtfav.getText();
        String gender = txtgender.getText();
        String height = txtheight.getText();
        String add1 = txtadd1.getText();
        String add2 = txtadd2.getText();
        String city = txtcity.getText();
        String state = txtstate.getText();
        String zip = txtzip.getText();
        String tel = txttel.getText();
        String fax = txtfax.getText();
        
        person.setFirst(first);
        person.setLast(last);
        person.setEmail(email);
        person.setPhone(phone);
        person.setLicno(licno);
        person.setLicst(licst);
        person.setSsn(ssn);
        person.setProf(prof);
        person.setBlood(blood);
        person.setHob(hob);
        person.setFav(fav);
        person.setGender(gender);
        person.setHeight(height);
        person.setAdd1(add1);
        person.setAdd2(add2);
        person.setCity(city);
        person.setState(state);
        person.setZip(zip);
        person.setTel(tel);
        person.setFax(fax);
        
        JOptionPane.showMessageDialog(this, "Personal Information Saved!!" , "Success", JOptionPane.PLAIN_MESSAGE);
        
        txtfirst.setText("");
        txtlast.setText("");
        txtemail.setText("");
        txtphone.setText("");
        txtlicno.setText("");
        txtlicst.setText("");
        txtssn.setText("");
        txtprof.setText("");
        txtblood.setText("");
        txthob.setText("");
        txtfav.setText("");
        txtgender.setText("");
        txtheight.setText("");
        txtadd1.setText("");
        txtadd2.setText("");
        txtcity.setText("");
        txtstate.setText("");
        txtzip.setText("");
        txttel.setText("");
        txtfax.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblFav;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbladd1;
    private javax.swing.JLabel lbladd2;
    private javax.swing.JLabel lblblood;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lblfirst;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lblhob;
    private javax.swing.JLabel lbllast;
    private javax.swing.JLabel lbllicno;
    private javax.swing.JLabel lbllicst;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblprof;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lbltel;
    private javax.swing.JLabel lblzip;
    private javax.swing.JTextField txtadd1;
    private javax.swing.JTextField txtadd2;
    private javax.swing.JTextField txtblood;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfav;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txtfirst;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txthob;
    private javax.swing.JTextField txtlast;
    private javax.swing.JTextField txtlicno;
    private javax.swing.JTextField txtlicst;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtprof;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables
}
