/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.Person;
import model.PersonDirectory;
import java.awt.CardLayout;
import model.Address;
import ui.ManagePerson.*;


/**
 *
 * @author mitra
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private PersonDirectory personDirectory;
   
    
    private Address h1;
    private Address h2;
    private Address h3;
    private Address h4;
    private Address h5;
    
    private Address w1;
    private Address w2;
    private Address w3;
    private Address w4;
    private Address w5;
               
    
    public MainJFrame() {
        initComponents();
        this.personDirectory = new PersonDirectory();
        this.h1 = new Address();
        this.w1 = new Address();
        
        this.h2 = new Address();
        this.w2 = new Address();
        
        this.h3 = new Address();
        this.w3 = new Address();
        
        this.h4 = new Address();
        this.w4 = new Address();
        
        this.h5 = new Address();
        this.w5 = new Address();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnOpenWorkArea = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnOpenWorkArea.setText("Open Work Area");
        btnOpenWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenWorkAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnOpenWorkArea)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnOpenWorkArea)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenWorkAreaActionPerformed
        // TODO add your handling code here:
        PersonMngWorkAreaJPanel panel = new PersonMngWorkAreaJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("PersonMngWorkAreaJPanel",panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOpenWorkAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenWorkArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
private void generateDemoData() {
        Person p1 = personDirectory.addPerson();
        p1.setFirstName("Aditya");
        p1.setLastName("Mitra");
        p1.setSsn(12345);
        p1.setAge(24);
        h1.setStreetAddress("S Huntington");
        h1.setCity("Boston");
        h1.setUnit(30);
        h1.setPhoneNumber("9082372993");
        h1.setState("MA");
        w1.setStreetAddress("S Huntington");
        w1.setCity("Boston");
        w1.setUnit(30);
        w1.setPhoneNumber("9082372993");
        w1.setState("MA");
        
     
        
        Person p2 = personDirectory.addPerson();
        p2.setFirstName("Kaustubh");
        p2.setLastName("Ambre");
        p2.setSsn(14345);
        p2.setAge(21);
        h2.setStreetAddress("S Huntington");
        h2.setCity("Boston");
        h2.setUnit(3);
        h2.setPhoneNumber("9072993");
        h2.setState("MA");
        w2.setStreetAddress("S Huntington");
        w2.setCity("Boston");
        w2.setUnit(32);
        w2.setPhoneNumber("907299313");
        w2.setState("MA");
        
        Person p3 = personDirectory.addPerson();
        p3.setFirstName("Mansi");
        p3.setLastName("Kamble");
        p3.setSsn(21345);
        p3.setAge(24);
        h3.setStreetAddress("S Huntington");
        h3.setCity("Boston");
        h3.setUnit(39);
        h3.setPhoneNumber("87671203");
        h3.setState("MA");
        w3.setStreetAddress("S Huntington");
        w3.setCity("Boston");
        w3.setUnit(39);
        w3.setPhoneNumber("87671203");
        w3.setState("MA");
        
        Person p4 = personDirectory.addPerson();
        p4.setFirstName("Vedant");
        p4.setLastName("Mane");
        p4.setSsn(2183);
        p4.setAge(26);
        h4.setStreetAddress("S Huntington");
        h4.setCity("Boston");
        h4.setUnit(9);
        h4.setPhoneNumber("21873741");
        h4.setState("MA");
        w4.setStreetAddress("S Huntington");
        w4.setCity("Boston");
        w4.setUnit(89);
        w4.setPhoneNumber("239123");
        w4.setState("MA");
        
        Person p5 = personDirectory.addPerson();
        p5.setFirstName("Abhinav");
        p5.setLastName("Gangurde");
        p5.setSsn(312312);
        p5.setAge(27);
        h5.setStreetAddress("S Huntington");
        h5.setCity("Boston");
        h5.setUnit(12);
        h5.setPhoneNumber("354231234");
        h5.setState("MA");
        w5.setStreetAddress("Brookline");
        w5.setCity("Boston");
        w5.setUnit(40);
        w5.setPhoneNumber("2394294");
        w5.setState("MA");
        
        
        
        
        
        
        
    }


}
