/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.Person;
import model.PersonDirectory;
import java.awt.CardLayout;
import java.util.Date;
import model.Address;
import ui.ManagePerson.*;


/**
 *
 * @author mitra
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private PersonDirectory personDirectory;
   
    
    private Address hAdd1;
    private Address hAdd2;
    private Address hAdd3;
    private Address hAdd4;
    private Address hAdd5;
    
    private Address wAdd1;
    private Address wAdd2;
    private Address wAdd3;
    private Address wAdd4;
    private Address wAdd5;
               
    
    public MainJFrame() {
        initComponents();
        this.personDirectory = new PersonDirectory();
        this.hAdd1 = new Address();
        this.wAdd1 = new Address();
        
        this.hAdd2 = new Address();
        this.wAdd2 = new Address();
        
        this.hAdd3 = new Address();
        this.wAdd3 = new Address();
        
        this.hAdd4 = new Address();
        this.wAdd4 = new Address();
        
        this.hAdd5 = new Address();
        this.wAdd5 = new Address();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnOpenWorkArea = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btnOpenWorkArea.setBackground(new java.awt.Color(255, 204, 204));
        btnOpenWorkArea.setText("Open Work Area");
        btnOpenWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenWorkAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnOpenWorkArea)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnOpenWorkArea)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenWorkAreaActionPerformed
        // TODO add your handling code here:
        PersonMngWorkAreaJPanel panel = new PersonMngWorkAreaJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("PersonMngWorkAreaJPanel",panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOpenWorkAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenWorkArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
private void generateDemoData() {
    
        Date date = new Date();
        
        Person p = personDirectory.addPerson();
        p.setFirstName("Aditya");
        p.setLastName("mitra");
        p.setSsn(112);
        p.setAge(24);
        p.setLastUpdated(date);
        
        hAdd1.setStreetAddress("30 South Huntington");
        hAdd1.setUnit(3);
        hAdd1.setCity("Boston");
        hAdd1.setState("MA");
        hAdd1.setZipCode(2130);
        hAdd1.setPhoneNumber("9082372993");
        
        p.setHomeAddress(hAdd1);
        
        wAdd1.setStreetAddress("40 S Huntington");
        wAdd1.setUnit(20);
        wAdd1.setCity("Jamaica Plain");
        wAdd1.setState("MA");
        wAdd1.setZipCode(1023);
        wAdd1.setPhoneNumber("2131283");
        
        p.setWorkAddress(wAdd1);
        
        p = personDirectory.addPerson();
        p.setFirstName("Mansi");
        p.setLastName("Kamble");
        p.setSsn(122);
        p.setAge(25);
        p.setLastUpdated(date);
        
        hAdd2.setStreetAddress("30 S Huntington");
        hAdd2.setUnit(4);
        hAdd2.setCity("Brooklyn");
        hAdd2.setState("MA");
        hAdd2.setZipCode(1412);
        hAdd2.setPhoneNumber("92384102");
        
        p.setHomeAddress(hAdd2);
        
        wAdd2.setStreetAddress("40 S Huington");
        wAdd2.setUnit(2);
        wAdd2.setCity("Roxbury");
        wAdd2.setState("MA");
        wAdd2.setZipCode(1012);
        wAdd2.setPhoneNumber("232112731");
        
        p.setWorkAddress(wAdd2);
        
        p = personDirectory.addPerson();
        p.setFirstName("Kaustubh");
        p.setLastName("Ambre");
        p.setSsn(23423);
        p.setAge(21);
        p.setLastUpdated(date);
        
        hAdd3.setStreetAddress("12 Summer Street");
        hAdd3.setUnit(3);
        hAdd3.setCity("Downtown");
        hAdd3.setState("MA");
        hAdd3.setZipCode(2311);
        hAdd3.setPhoneNumber("12312341");
        
        p.setHomeAddress(hAdd3);
        
        wAdd3.setStreetAddress("12 Winter Streer");
        wAdd3.setUnit(2);
        wAdd3.setCity("Downtown");
        wAdd3.setState("MA");
        wAdd3.setZipCode(2311);
        wAdd3.setPhoneNumber("232112731");
        
        p.setWorkAddress(wAdd3);
        
        p = personDirectory.addPerson();
        p.setFirstName("Vedant");
        p.setLastName("Mane");
        p.setSsn(23941);
        p.setAge(26);
        p.setLastUpdated(date);
        
        hAdd4.setStreetAddress("12 Heath Street");
        hAdd4.setUnit(3);
        hAdd4.setCity("Riverway");
        hAdd4.setState("MA");
        hAdd4.setZipCode(123);
        hAdd4.setPhoneNumber("243241");
        
        p.setHomeAddress(hAdd4);
        
        wAdd4.setStreetAddress("21 Heath Street");
        wAdd4.setUnit(2);
        wAdd4.setCity("Riverway");
        wAdd4.setState("MA");
        wAdd4.setZipCode(234);
        wAdd4.setPhoneNumber("23412412");
        
        p.setWorkAddress(wAdd4);
        
        p = personDirectory.addPerson();
        p.setFirstName("Caden");
        p.setLastName("Caver");
        p.setSsn(1231);
        p.setAge(19);
        p.setLastUpdated(date);
        
        hAdd5.setStreetAddress("45 Forest Hills");
        hAdd5.setUnit(3);
        hAdd5.setCity("Jamaica Plain");
        hAdd5.setState("MA");
        hAdd5.setZipCode(12312);
        hAdd5.setPhoneNumber("218391");
        
        p.setHomeAddress(hAdd5);
        
        wAdd5.setStreetAddress("78 Boston Harbour");
        wAdd5.setUnit(21);
        wAdd5.setCity("Boston");
        wAdd5.setState("MA");
        wAdd5.setZipCode(21);
        wAdd5.setPhoneNumber("231231");
        
        p.setWorkAddress(wAdd5);
                
        
        
        
        
       
        
        
        
        
        
        
        
    }


}
